first part
uPhoenix/Maze-Adventures pull request #4
Opened 2018-01-03 16:15 UTC by belozerovany

2018-01-03 16:16 UTC, belozerovany commented
@uPhoenix  Please check the first part game without "vuex js "and "TDD"

2018-01-03 16:21 UTC, uPhoenix requested changes

2018-01-03 16:21 UTC, uPhoenix commented on src/components/MainMenu.vue
> +      <router-link to="/teststore" class="button button-huge block-mobile">TEST STORE</router-link>
No test stuff in production

2018-01-04 15:57 UTC, belozerovany commented
@uPhoenix  hello pleas check part without test part

2018-01-09 16:57 UTC, belozerovany commented
@uPhoenix  
Good day.
Zahar pleas check  our project, we are added unit tests

2018-01-10 10:22 UTC, merged